# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-06 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='band',
            name='incorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='incorrect',
            field=models.IntegerField(default=0),
        ),
    ]
